Array Attributes:
ndim = rank (dimensions).

shape = tuple of dimensions.

size = total number of elements.

In [1]:
import numpy as np

arr = np.arange(12).reshape(3, 4)

print("Array:\n", arr)
print("ndim  :", arr.ndim)   # Number of dimensions
print("shape :", arr.shape)  # Rows, Columns
print("size  :", arr.size)   # Total elements
print("dtype :", arr.dtype)  # Data type

Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ndim  : 2
shape : (3, 4)
size  : 12
dtype : int64


In [2]:
arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


`np.eye`
 Creates a **2D identity-like array**.
 
 Ones on the *k-th diagonal*, zeros elsewhere.
 
 Parameters:
 
   `N` → number of rows
   
   `M` → number of columns (defaults to `N`)
   
   `k` → index of diagonal (0 = main, >0 above, <0 below)

In [3]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



**np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0, *, device=None)**

From NumPy How to Partition / Array Creation Routines and the linspace doc.

Returns num evenly spaced samples over the interval [start, stop] (inclusive by default) 

If endpoint=False, the stop is not included; this changes the step size accordingly. 

If retstep=True, returns a tuple (samples, step) where step is the spacing between samples. 

The dtype, if not provided, is inferred from start and stop. 
If integer types are used, behavior was changed in recent versions (rounding toward –∞ instead of 0) when casting. 

Good when we want a fixed number of points in an interval, especially for plotting. If you want a specific step size, arange can be used but may cause floating point rounding issues

In [4]:
arr = np.linspace(0, 1, 5)  # 5 points between 0 and 1
print(arr)

[0.   0.25 0.5  0.75 1.  ]


`np.arange`
- Returns values in `[start, stop)` with given `step`.
- Faster and simpler than `linspace` for integer steps.
- Floating-point `step` may cause rounding issues.
- Use `linspace` if you need an exact number of points.

In [5]:
arr = np.arange(0, 10, 2)
print(arr)

[0 2 4 6 8]


`np.zeros` & `np.ones`
- Return arrays filled with `0`s or `1`s.
- Default dtype: `float64`.
- Shape must be provided as a tuple.
- Useful for initialization before filling with data.

In [6]:
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
print(zeros, "\n", ones)

[[0. 0. 0.]
 [0. 0. 0.]] 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


`np.random`
- Random sampling functions:
  - `rand(m, n)` → uniform in [0,1)
  - `randn(m, n)` → standard normal (mean=0, std=1)
  - `randint(low, high, size)` → random integers
- Use `np.random.seed()` for reproducibility.

In [7]:
rand_uniform = np.random.rand(2, 3)   # Uniform [0,1)
rand_normal  = np.random.randn(2, 3)  # Standard Normal
rand_ints    = np.random.randint(0, 10, (2, 3)) # Random integers
print(rand_uniform, "\n", rand_normal, "\n", rand_ints)

[[0.15635049 0.59326071 0.92786909]
 [0.92218059 0.94993722 0.17763221]] 
 [[-0.20406288  0.74748389 -0.72698872]
 [-0.47560112 -1.22968783  1.89112011]] 
 [[8 3 3]
 [1 7 5]]


 `np.diag`
- If input is **1D**: creates a 2D diagonal matrix.
- If input is **2D**: extracts the k-th diagonal.
- `k=0` → main diagonal, positive above, negative below.

In [8]:
d = np.diag([1, 2, 3])
print(d)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [33]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

d = np.diag(arr2d)   # Extracts the main diagonal
print(d)

[1 5 9]


 `np.indices`
- Generates a grid of indices for given shape.
- Returns array of shape `(len(dimensions),) + dimensions`.
- If `sparse=True`, returns tuple of sparse index arrays (saves memory).
- Useful in **image processing & coordinate grids**.

In [9]:
idx = np.indices((3, 3))
print("Row indices:\n", idx[0])
print("Column indices:\n", idx[1])

Row indices:
 [[0 0 0]
 [1 1 1]
 [2 2 2]]
Column indices:
 [[0 1 2]
 [0 1 2]
 [0 1 2]]


 Quick Reminders
- `np.linspace` → safer for float intervals.  
- `np.arange` → better for integer steps.  
- Default dtype is often `float64` (unless specified).  
- `order='C'` (row-major) vs `order='F'` (column-major) matters for memory layout.

np.array → Convert Python list → NumPy array.

np.eye → Identity matrix.

np.linspace → Evenly spaced values (good for plotting).

np.arange → Range with step (watch out for float rounding).

np.zeros & np.ones → Quick initialization.

np.random → Random sampling (set seed for reproducibility).

np.diag → Build/extract diagonals.

np.indices → Generate coordinate grids.

Note:

Vandermonde matrix often used in polynomial fitting.

Each row is powers of input vector.

In [10]:
x = np.array([1, 2, 3, 5])
V = np.vander(x, N=4, increasing=True)
print(V)

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   5  25 125]]


Indexing and Slicing

In [35]:
# 1D Example
arr = np.arange(10)
print(arr[0])     # First element
print(arr[-1])    # Last element
print(arr[2:6])   # Slice
print(arr[::2])   # Every 2nd element

0
9
[2 3 4 5]
[0 2 4 6 8]


In [36]:
#2D Example
arr = np.arange(1, 13).reshape(3, 4)
print(arr)

print(arr[1, 2])      # Single element
print(arr[1, :])      # Entire row
print(arr[:, 2])      # Entire column
print(arr[0:2, 1:3])  # Subarray

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
7
[5 6 7 8]
[ 3  7 11]
[[2 3]
 [6 7]]


Creating Multidimensional Arrays

Note: NumPy can handle N-dimensional arrays. .shape shows dimensions.

In [37]:
arr3d = np.array([[[1, 2], [3, 4]], 
                  [[5, 6], [7, 8]]])

print(arr3d.shape)   # (2, 2, 2)
print(arr3d[0, 1, 1])  # Accessing element (4)

(2, 2, 2)
4
